### ISSUE TITLE
Normalizzazione

### ISSUE THREAD

**Issue by andreadelfante** [fabiana001/UrlOrganizer#1]
- http://stats.stackexchange.com/questions/200070/in-general-does-normalization-mean-to-normalize-the-samples-or-features
- http://stackoverflow.com/questions/29090749/how-to-choose-the-right-normalization-method-for-the-right-dataset
- http://stats.stackexchange.com/questions/175463/what-is-the-purpose-of-row-normalization
- https://www.quora.com/Should-I-do-normalization-to-word-embeddings-from-word2vec-if-I-want-to-do-semantic-tasks

**Comment by fabiana001** [comment]
@andreadelfante tesi magistrale? :)

**Comment by andreadelfante** [comment]
Ciao @fabiana001 ! No stavo pulendo un pò di issue aperte! ahahah
